auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: broker:29092
    kafkaConnect:
    - address: http://connect:8083
      name: connect-local
    ksqldbServer: http://ksqldb-server:8088
    name: kafka-local
    properties: {}
    readOnly: false
    schemaRegistry: http://schema-registry:8081
rbac:
  roles: []
webclient: {}